language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  # pip install .
# command to run tests
script: python test_run.py postman-echo.com release1
deploy:
  provider: releases
  api_key: ${api_key}
  file: "requirements.txt"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
notifications:
  slack:
    rooms:
      - automation-sravan:ileYh2eClUTRWYguPVX4xgfa
      - automation-sravan:ileYh2eClUTRWYguPVX4xgfa#general
      - automation-sravan:ileYh2eClUTRWYguPVX4xgfa#random
  email:
    recipients:
      - sravan.bade1@gmail.com
      - sravankumarreddy.bade@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
